name: Build, Test, Release
on: [ push ]

jobs:
  build:
    name: Build
    runs-on: windows-2025
    steps:
      # Setup
      - uses: actions/checkout@v5

      - name: Toolchain [Windows]
        shell: sh
        run: |
          set -ux
          echo ::group::Toolchain
          # Install updated LLVM (and hide spammy progress bar)
          # nb: clang 22 is busted
          winget install --accept-source-agreements --silent -e --id=LLVM.LLVM --version=21.1.8 | tr '\r' '\n' | grep -Ev --line-buffered '^[ -\/|]+$'
          # You want the mingw version of ninja, not the msys version. The msys version uses
          # `CMD.EXE` and does not work with the cmake Ninja generator.
          ARCH=x86_64
          /c/msys64/usr/bin/pacman -S --noconfirm \
            mingw-w64-$ARCH-boost \
            mingw64/mingw-w64-$ARCH-cmake \
            mingw64/mingw-w64-$ARCH-ninja \
          ;
          echo "/c/msys64/mingw64/bin" >> "$GITHUB_PATH"
          echo "/c/msys64/usr/bin" >> "$GITHUB_PATH"
          echo ::endgroup::

          echo ::group::import std hack
          # /c/Program Files/Microsoft Visual Studio/2022/Enterprise
          VISUAL_STUDIO_PATH=$(cygpath "$(vswhere | grep installationPath: | cut -c19-)")
          # /c/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207
          MSVC_PATH="$VISUAL_STUDIO_PATH/VC/Tools/MSVC/$(ls "$VISUAL_STUDIO_PATH/VC/Tools/MSVC" | sort -V | tail -1)"

          # Make the `import std` interface manifest
          MANIFEST_JSON=$(cat <<EOF
          {
            "version": 1,
            "revision": 1,
            "modules": [
              { "logical-name": "std", "source-path": "SOURCE_PATH", "is-std-library": true }
            ],
            "local-arguments": {
              "system-include-directories": [ "INCLUDE_PATH" ]
            }
          }
          EOF
          )
          # World record backslashes
          MANIFEST_JSON=$(sed "s#SOURCE_PATH#$(cygpath -w "$MSVC_PATH/modules/std.ixx" | sed 's \\ \\\\\\\\\\\\\\\\ g')#")
          # This wants a Unix path but the other wants a Windows path
          MANIFEST_JSON=$(sed "s#INCLUDE_PATH#$MSVC_PATH/modules#")
          echo "$MANIFEST_JSON" | tee ms-stl.modules.json

          # Patch cmake
          patch --batch --unified /c/msys64/mingw64/share/cmake/Modules/Compiler/Clang-CXX-CXXImportStd.cmake <<"EOF"
          @@ -4,10 +4,8 @@
             elseif (CMAKE_CXX_STANDARD_LIBRARY STREQUAL "libstdc++")
               set(_clang_modules_json_impl "libstdc++")
             else ()
          -    set("${variable}"
          -      "set(CMAKE_CXX${std}_COMPILER_IMPORT_STD_NOT_FOUND_MESSAGE \"Only `libc++` and `libstdc++` are supported\")\n"
          -      PARENT_SCOPE)
          -    return ()
          +    set(_clang_modules_json_impl "libc++")
          +    set(CMAKE_CXX_STDLIB_MODULES_JSON ms-stl.modules.json)
             endif ()

             if (CMAKE_CXX_STDLIB_MODULES_JSON)
          EOF
          echo ::endgroup::

      - name: Configure
        shell: sh
        run: |
          set -ux
          CMAKE_C_COMPILER=$(which clang.exe)
          CMAKE_CXX_COMPILER=$(which clang++.exe)
          CMAKE_MAKE_PROGRAM=$(which ninja.exe)
          CMAKE_PREFIX_PATH=C:/msys64/mingw64/lib/cmake
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER="$CMAKE_C_COMPILER" \
            -DCMAKE_CXX_COMPILER="$CMAKE_CXX_COMPILER" \
            -DCMAKE_MAKE_PROGRAM="$CMAKE_MAKE_PROGRAM" \
            -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH" \
            -B build \
            -G Ninja \
          ;
      - name: Build
        shell: sh
        run: ninja -C build

      - name: Test
        shell: sh
        run: build/foo.exe

      - uses: laverdet/console@v1
        if: failure()
